# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Neoplanetz
tagline:          'To wide knowledge'
description:      'New Neoplanetz Blog'
url:              https://neoplanetz.github.io/
baseurl:          /

author:
  name:           'YoHan Jung'
  url:            https://neoplanetz.github.io/

paginate:         5

# Custom vars
version:          1.0

github:           
  repo:           https://github.com/Neoplanetz/neoplanetz.github.io/
